import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-background': '#191c1e',
        'inverse-on-surface': '#eff1f3',
        'primary-fixed-dim': '#97ccfe',
        'on-primary-fixed': '#001d32',
        'on-surface': '#191c1e',
        'surface-variant': '#e0e3e5',
        'tertiary': '#24333e',
        'surface': '#f7f9fb',
        'on-tertiary-fixed': '#0e1d28',
        'on-tertiary-container': '#a8b8c6',
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'outline-variant': '#c1c7d0',
        'ink-black': '#1D1D1D',
        'inverse-primary': '#97ccfe',
        'on-error': '#ffffff',
        'primary-container': '#004b76',
        'background': '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'deep-navy': '#004B76',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#394955',
        'vibrant-red': '#FA4B37',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'charcoal-slate': '#2E3D49',
        'surface-bright': '#f7f9fb',
        'on-secondary-container': '#fffbff',
        'tertiary-container': '#3a4955',
        'secondary-container': '#da3424',
        'primary': '#003453',
        'outline': '#71787f',
        'surface-container': '#eceef0',
        'surface-dim': '#d8dadc',
        'on-primary-container': '#86bbec',
        'inverse-surface': '#2d3133',
        'secondary': '#b6180c',
        'secondary-fixed': '#ffdad4',
        'on-error-container': '#93000a',
        'surface-tint': '#28628f',
        'on-secondary-fixed': '#410000',
        'on-surface-variant': '#41474e',
        'surface-container-highest': '#e0e3e5',
        'on-secondary-fixed-variant': '#930100',
        'primary-fixed': '#cde5ff',
        'on-primary-fixed-variant': '#004a75',
        'tertiary-fixed-dim': '#b8c8d7',
        'tertiary-fixed': '#d4e4f4',
        'secondary-fixed-dim': '#ffb4a8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'stack-sm': '8px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        'stack-lg': '32px',
        'gutter': '24px',
        'section-gap': '120px',
        'stack-md': '16px',
      },
      fontFamily: {
        caption: ['Inter', 'sans-serif'],
        'display-italic': ['Playfair Display', 'serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'display-italic': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-xl': ['60px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
export default config
