export type FlowNode = {
  title: string
  description: string
}

export type SubsystemPageData = {
  slug: string
  title: string
  eyebrow: string
  subtitle: string
  description: string
  icon: string
  visualImage: string
  flowTitle: string
  flowDescription: string
  flowNodes: FlowNode[]
  modules: string[]
  impacts: { value: string; label: string; detail: string }[]
  framework: string[]
  governance: string[]
  industries: string[]
  cta: string
}

export const subsystemPages: SubsystemPageData[] = [
  {
    slug: 'erp',
    title: 'ERP System',
    eyebrow: 'Enterprise Resource Planning',
    subtitle: 'A unified operating backbone for finance, inventory, procurement, HR, and leadership reporting.',
    description: 'Axinex ERP ecosystems centralize business operations into a secure, modular platform where departments work from one source of truth and leadership gains real-time visibility.',
    icon: 'dashboard',
    visualImage: '/assets/ERP.jpeg',
    flowTitle: 'ERP Operating Lifecycle',
    flowDescription: 'A connected enterprise loop that moves data from departments into approvals, controls, and executive dashboards.',
    flowNodes: [
      { title: 'Business Units', description: 'Finance, HR, sales, procurement, inventory, and operations feed structured activity into the platform.' },
      { title: 'ERP Core', description: 'Role-based modules standardize workflows, records, approvals, and data ownership.' },
      { title: 'Approval Layer', description: 'Automated validations, authorization rules, and escalation paths keep transactions controlled.' },
      { title: 'Reporting Hub', description: 'Dashboards, MIS reports, and KPI views convert operations into leadership intelligence.' },
      { title: 'Optimization', description: 'Process insights guide continuous improvements, automation, and future module expansion.' },
    ],
    modules: ['Finance Management', 'Inventory Control', 'Procurement Workflows', 'HR Operations', 'Executive Dashboards', 'Role-Based Access'],
    impacts: [
      { value: '1', label: 'Source of Truth', detail: 'Centralized operational records across departments.' },
      { value: '40%', label: 'Less Manual Work', detail: 'Reduced duplicate entries and spreadsheet dependency.' },
      { value: '24/7', label: 'Visibility', detail: 'Live operational tracking for authorized teams.' },
    ],
    framework: ['Requirement mapping', 'Module architecture', 'Workflow configuration', 'Data migration', 'Testing and training', 'Go-live support'],
    governance: ['Approval controls', 'Role permissions', 'Audit-ready activity trails', 'Data validation standards'],
    industries: ['Manufacturing', 'Trading and distribution', 'Professional services', 'Multi-branch operations'],
    cta: 'Build a connected ERP foundation for your enterprise.',
  },
  {
    slug: 'crm',
    title: 'CRM System',
    eyebrow: 'Customer Relationship Management',
    subtitle: 'A complete customer lifecycle platform for leads, sales activity, engagement, service, and revenue insight.',
    description: 'Axinex CRM solutions help teams capture opportunities, structure follow-ups, improve customer visibility, and build reliable sales and service pipelines.',
    icon: 'group',
    visualImage: '/assets/CRM.jpeg',
    flowTitle: 'Customer Lifecycle Flow',
    flowDescription: 'From lead intake to long-term engagement, each customer interaction becomes trackable and measurable.',
    flowNodes: [
      { title: 'Lead Intake', description: 'Capture enquiries from web, campaigns, calls, referrals, and internal sources.' },
      { title: 'Qualification', description: 'Score leads, assign owners, and identify priority opportunities.' },
      { title: 'Pipeline', description: 'Track stages, proposals, meetings, and deal movement with clear ownership.' },
      { title: 'Engagement', description: 'Automate follow-ups, reminders, communication notes, and service continuity.' },
      { title: 'Insights', description: 'Measure conversion, customer health, sales velocity, and relationship value.' },
    ],
    modules: ['Lead Management', 'Sales Pipeline', 'Customer Profiles', 'Follow-Up Automation', 'Service History', 'Revenue Reports'],
    impacts: [
      { value: '360', label: 'Customer View', detail: 'One profile for contact, activity, and service history.' },
      { value: 'Faster', label: 'Follow-Ups', detail: 'Structured reminders reduce missed opportunities.' },
      { value: 'Clear', label: 'Pipeline', detail: 'Better visibility into active deals and bottlenecks.' },
    ],
    framework: ['Customer journey discovery', 'Pipeline design', 'Automation setup', 'Integration planning', 'Team training', 'Performance review'],
    governance: ['Owner-based access', 'Communication logs', 'Customer data controls', 'Sales activity audit history'],
    industries: ['B2B services', 'Real estate', 'Education', 'Healthcare and wellness', 'Technology companies'],
    cta: 'Transform customer relationships into measurable growth.',
  },
  {
    slug: 'ams',
    title: 'AMS Platform',
    eyebrow: 'Annual Maintenance Support',
    subtitle: 'A structured support and maintenance ecosystem for tickets, SLAs, preventive care, and service reporting.',
    description: 'Axinex AMS platforms keep deployed systems stable through clear support workflows, priority handling, maintenance schedules, and transparent resolution tracking.',
    icon: 'verified_user',
    visualImage: '/assets/AMS.jpeg',
    flowTitle: 'Maintenance Lifecycle',
    flowDescription: 'Every issue moves through a controlled path from detection to resolution, reporting, and prevention.',
    flowNodes: [
      { title: 'Issue Detection', description: 'Capture incidents from users, monitoring, calls, emails, or support portals.' },
      { title: 'Ticket Routing', description: 'Assign priority, ownership, SLA category, and required resolution path.' },
      { title: 'Resolution', description: 'Track work notes, fixes, approvals, and communication until closure.' },
      { title: 'Preventive Care', description: 'Schedule updates, audits, backups, health checks, and performance reviews.' },
      { title: 'Service Reports', description: 'Summarize SLA health, recurring issues, response quality, and improvement actions.' },
    ],
    modules: ['Ticket Desk', 'SLA Monitoring', 'Preventive Maintenance', 'Knowledge Base', 'Escalation Matrix', 'Service Analytics'],
    impacts: [
      { value: 'SLA', label: 'Controlled Support', detail: 'Priority-based response and escalation management.' },
      { value: 'Lower', label: 'Downtime Risk', detail: 'Preventive maintenance reduces recurring failures.' },
      { value: 'Clear', label: 'Reporting', detail: 'Service performance is visible to stakeholders.' },
    ],
    framework: ['Support scope definition', 'SLA configuration', 'Ticket workflow setup', 'Monitoring alignment', 'Review cadence', 'Continuous improvement'],
    governance: ['SLA policies', 'Resolution logs', 'Change records', 'Backup and update schedules'],
    industries: ['Software products', 'Enterprise portals', 'Government platforms', 'Internal business systems'],
    cta: 'Keep critical systems stable with structured maintenance support.',
  },
  {
    slug: 'migration-services',
    title: 'Migration Services',
    eyebrow: 'Modernization & Transition',
    subtitle: 'A controlled migration framework for data, applications, infrastructure, and legacy system modernization.',
    description: 'Axinex migration programs help organizations move from outdated or fragmented environments into secure, scalable, and future-ready platforms without losing operational continuity.',
    icon: 'rocket',
    visualImage: '/assets/Migration.jpeg',
    flowTitle: 'Infrastructure Transition Flow',
    flowDescription: 'A staged migration path that protects data, validates movement, and supports stable adoption.',
    flowNodes: [
      { title: 'Current Audit', description: 'Assess systems, data quality, dependencies, risks, and business continuity needs.' },
      { title: 'Migration Blueprint', description: 'Define target architecture, mapping rules, security controls, and rollout strategy.' },
      { title: 'Secure Transfer', description: 'Move data and workloads through controlled batches with validation gates.' },
      { title: 'Validation', description: 'Test records, integrations, user flows, access controls, and operational accuracy.' },
      { title: 'Go Live', description: 'Launch with monitoring, rollback planning, training, and post-migration support.' },
    ],
    modules: ['Legacy Assessment', 'Data Mapping', 'Cloud Migration', 'Application Transition', 'Validation Testing', 'Post-Migration Support'],
    impacts: [
      { value: 'Low', label: 'Disruption', detail: 'Staged transitions protect business continuity.' },
      { value: 'Secure', label: 'Data Movement', detail: 'Validation checkpoints reduce migration risk.' },
      { value: 'Future', label: 'Ready Stack', detail: 'Modern architecture supports long-term scaling.' },
    ],
    framework: ['Discovery audit', 'Target design', 'Migration planning', 'Pilot migration', 'Full transition', 'Stabilization'],
    governance: ['Data validation', 'Access review', 'Rollback planning', 'Migration audit logs'],
    industries: ['Legacy enterprises', 'Growing SaaS teams', 'Cloud modernization projects', 'Data-heavy operations'],
    cta: 'Move from legacy complexity to a modern digital foundation.',
  },
  {
    slug: 'cloud-transformation',
    title: 'Cloud Transformation Services',
    eyebrow: 'Cloud Modernization',
    subtitle: 'A cloud adoption roadmap for scalable platforms, resilient workloads, and controlled digital growth.',
    description: 'Axinex helps organizations assess cloud readiness, design target architectures, migrate workloads, and optimize operations for reliability and scale.',
    icon: 'cloud',
    visualImage: '/assets/cloud_transformation_services.jpeg',
    flowTitle: 'Cloud Adoption Architecture',
    flowDescription: 'A progressive cloud journey from readiness assessment to governed, optimized operations.',
    flowNodes: [
      { title: 'Readiness', description: 'Evaluate applications, data, security posture, costs, and workload suitability.' },
      { title: 'Blueprint', description: 'Create landing zones, network design, access models, and deployment standards.' },
      { title: 'Migration', description: 'Move workloads through staged, tested, and monitored transition paths.' },
      { title: 'Optimization', description: 'Tune performance, cost, reliability, and operational automation.' },
      { title: 'Governance', description: 'Standardize controls, monitoring, compliance, and scaling practices.' },
    ],
    modules: ['Cloud Readiness', 'Landing Zone Design', 'Workload Migration', 'Cost Optimization', 'Cloud Monitoring', 'Governance Controls'],
    impacts: [
      { value: 'Scale', label: 'On Demand', detail: 'Infrastructure grows with business requirements.' },
      { value: 'Resilient', label: 'Operations', detail: 'Cloud architecture improves continuity and recovery.' },
      { value: 'Optimized', label: 'Spend', detail: 'Cost visibility and right-sizing reduce waste.' },
    ],
    framework: ['Assessment', 'Architecture', 'Pilot', 'Migration', 'Optimization', 'Governance'],
    governance: ['IAM controls', 'Monitoring standards', 'Backup policies', 'Cost governance'],
    industries: ['SaaS platforms', 'Retail operations', 'Education technology', 'Healthcare systems'],
    cta: 'Modernize your platform with a secure cloud foundation.',
  },
  {
    slug: 'cloud-infrastructure-management',
    title: 'Cloud Infrastructure Management',
    eyebrow: 'Managed Cloud Operations',
    subtitle: 'A governed infrastructure operations model for compute, storage, network, monitoring, and reliability.',
    description: 'Axinex manages cloud environments with structured monitoring, performance optimization, incident handling, and reliability planning.',
    icon: 'terminal',
    visualImage: '/assets/cloud_infrastructure_management.jpeg',
    flowTitle: 'Managed Infrastructure Loop',
    flowDescription: 'A continuous operations cycle that keeps cloud resources visible, stable, and optimized.',
    flowNodes: [
      { title: 'Infrastructure Layer', description: 'Compute, storage, network, databases, and integrations are mapped and organized.' },
      { title: 'Monitoring', description: 'Health, uptime, capacity, cost, and performance signals are tracked.' },
      { title: 'Response', description: 'Alerts move through triage, ownership, escalation, and resolution workflows.' },
      { title: 'Optimization', description: 'Usage and performance insights guide right-sizing and improvement actions.' },
      { title: 'Reporting', description: 'Reliability, incidents, costs, and compliance posture are summarized for stakeholders.' },
    ],
    modules: ['Resource Management', 'Monitoring Dashboards', 'Incident Response', 'Backup Planning', 'Cost Governance', 'Reliability Reports'],
    impacts: [
      { value: '99.9%', label: 'Reliability Focus', detail: 'Monitoring and response reduce operational risk.' },
      { value: 'Clear', label: 'Ownership', detail: 'Defined support paths prevent operational confusion.' },
      { value: 'Lean', label: 'Cloud Spend', detail: 'Optimization reduces unnecessary resource usage.' },
    ],
    framework: ['Environment audit', 'Monitoring setup', 'Operations model', 'Incident playbooks', 'Optimization cycle', 'Monthly reporting'],
    governance: ['Backup policy', 'Alert escalation', 'Access reviews', 'Cost controls'],
    industries: ['Cloud-native companies', 'Enterprise IT teams', 'Managed platforms', 'Digital products'],
    cta: 'Run cloud infrastructure with clarity, control, and reliability.',
  },
  {
    slug: 'identity-access-management',
    title: 'Identity & Access Management',
    eyebrow: 'IAM Security',
    subtitle: 'A controlled identity layer for users, roles, permissions, authentication, and compliance visibility.',
    description: 'Axinex IAM solutions help organizations protect systems with structured identity controls, role-based access, and review-ready permission governance.',
    icon: 'lock',
    visualImage: '/assets/IAM.jpeg',
    flowTitle: 'Identity Control Flow',
    flowDescription: 'Every user journey moves through identity verification, permission assignment, and ongoing review.',
    flowNodes: [
      { title: 'Identity Source', description: 'Users, teams, vendors, and systems are registered with clear ownership.' },
      { title: 'Role Mapping', description: 'Permissions are grouped around job roles, departments, and access needs.' },
      { title: 'Authentication', description: 'Login policies, verification layers, and session controls protect entry points.' },
      { title: 'Access Review', description: 'Permission usage, exceptions, and changes are monitored and reviewed.' },
      { title: 'Compliance Logs', description: 'Audit trails preserve access history for governance and security reviews.' },
    ],
    modules: ['User Directory', 'Role-Based Access', 'Authentication Controls', 'Permission Reviews', 'Access Logs', 'Policy Enforcement'],
    impacts: [
      { value: 'Least', label: 'Privilege', detail: 'Users receive only the access they need.' },
      { value: 'Audit', label: 'Ready', detail: 'Access activity is traceable and reviewable.' },
      { value: 'Secure', label: 'Identity Layer', detail: 'Authentication controls reduce unauthorized access.' },
    ],
    framework: ['Identity audit', 'Role design', 'Policy configuration', 'Authentication setup', 'Review cadence', 'Compliance reporting'],
    governance: ['Least privilege', 'MFA readiness', 'Access logs', 'Quarterly permission reviews'],
    industries: ['Finance', 'Healthcare', 'SaaS platforms', 'Enterprise operations'],
    cta: 'Strengthen enterprise access with governed identity controls.',
  },
  {
    slug: 'data-management-system',
    title: 'Data Management System',
    eyebrow: 'Data Operations',
    subtitle: 'A governed data foundation for collection, cleaning, storage, access, and enterprise reporting.',
    description: 'Axinex data management systems organize business information into reliable structures that support reporting, workflows, compliance, and future analytics.',
    icon: 'analytics',
    visualImage: '/assets/data_management_system.jpeg',
    flowTitle: 'Data Governance Flow',
    flowDescription: 'A clean data lifecycle from source capture to business-ready access and governance.',
    flowNodes: [
      { title: 'Data Sources', description: 'Applications, forms, databases, files, and third-party systems feed controlled inputs.' },
      { title: 'Cleansing', description: 'Validation, deduplication, normalization, and quality checks improve reliability.' },
      { title: 'Storage Layer', description: 'Structured repositories organize records around business ownership and use cases.' },
      { title: 'Governance', description: 'Access rules, retention policies, and data standards protect quality and compliance.' },
      { title: 'Business Access', description: 'Teams consume trusted datasets through dashboards, reports, APIs, and workflows.' },
    ],
    modules: ['Data Capture', 'Quality Rules', 'Central Storage', 'Data Governance', 'Access Controls', 'Data Services'],
    impacts: [
      { value: 'Trusted', label: 'Records', detail: 'Improved data quality supports confident decisions.' },
      { value: 'Faster', label: 'Reporting', detail: 'Structured data reduces manual report preparation.' },
      { value: 'Governed', label: 'Access', detail: 'Data ownership and access become controlled.' },
    ],
    framework: ['Source mapping', 'Data model design', 'Quality rules', 'Storage setup', 'Access enablement', 'Governance reviews'],
    governance: ['Retention rules', 'Access permissions', 'Quality thresholds', 'Audit logs'],
    industries: ['Data-heavy enterprises', 'Education', 'Healthcare', 'Operations teams'],
    cta: 'Build a reliable foundation for enterprise data intelligence.',
  },
  {
    slug: 'business-intelligence',
    title: 'Business Intelligence',
    eyebrow: 'BI & Decision Systems',
    subtitle: 'A leadership intelligence layer for KPIs, dashboards, forecasting, and operational decision-making.',
    description: 'Axinex BI platforms turn fragmented data into clear, visual, and actionable management insight for executives and operational teams.',
    icon: 'trending_up',
    visualImage: '/assets/business_intellegence.jpeg',
    flowTitle: 'Insight Delivery Flow',
    flowDescription: 'Data moves through modeling, visualization, and interpretation to become decision intelligence.',
    flowNodes: [
      { title: 'Data Collection', description: 'Business systems, data warehouses, and operational sources are connected.' },
      { title: 'KPI Modeling', description: 'Metrics are defined around goals, departments, and leadership priorities.' },
      { title: 'Dashboards', description: 'Interactive views present performance, trends, and exceptions clearly.' },
      { title: 'Insight Engine', description: 'Comparisons, drilldowns, and forecasting reveal business opportunities.' },
      { title: 'Decision Reports', description: 'Scheduled reports and executive summaries support action and accountability.' },
    ],
    modules: ['KPI Frameworks', 'Executive Dashboards', 'Operational Reports', 'Trend Analysis', 'Forecasting Views', 'Drilldown Insights'],
    impacts: [
      { value: 'Real', label: 'Visibility', detail: 'Leaders see key performance without manual compilation.' },
      { value: 'Better', label: 'Decisions', detail: 'Consistent KPIs reduce guesswork.' },
      { value: 'Early', label: 'Signals', detail: 'Trends and exceptions surface before issues grow.' },
    ],
    framework: ['KPI discovery', 'Data connection', 'Dashboard design', 'Report automation', 'User training', 'Insight review'],
    governance: ['Metric definitions', 'Data lineage', 'Role-based dashboards', 'Report controls'],
    industries: ['Leadership teams', 'Sales operations', 'Finance departments', 'Manufacturing analytics'],
    cta: 'Turn operational data into executive intelligence.',
  },
  {
    slug: 'workflow-automation-system',
    title: 'Workflow Automation System',
    eyebrow: 'Process Automation',
    subtitle: 'A configurable workflow engine for approvals, task routing, forms, alerts, and operational accountability.',
    description: 'Axinex workflow automation systems reduce manual effort by turning repeated processes into structured, trackable, and measurable digital flows.',
    icon: 'hub',
    visualImage: '/assets/workflow_automation_system.jpeg',
    flowTitle: 'Automation Workflow',
    flowDescription: 'Manual process steps become event-driven tasks with routing, approvals, alerts, and performance tracking.',
    flowNodes: [
      { title: 'Process Input', description: 'Forms, requests, records, or events initiate structured workflows.' },
      { title: 'Trigger Rules', description: 'Conditions determine routing, priority, ownership, and required approvals.' },
      { title: 'Task Engine', description: 'Work moves between users, teams, and systems with clear deadlines.' },
      { title: 'Approval Layer', description: 'Decision points preserve control, audit history, and escalation paths.' },
      { title: 'Performance Tracking', description: 'Cycle time, bottlenecks, exceptions, and completion quality are measured.' },
    ],
    modules: ['Digital Forms', 'Task Routing', 'Approval Chains', 'Alerts and Reminders', 'Escalations', 'Workflow Analytics'],
    impacts: [
      { value: 'Faster', label: 'Turnaround', detail: 'Digital routing reduces waiting and handoffs.' },
      { value: 'Clear', label: 'Ownership', detail: 'Every step has assigned responsibility.' },
      { value: 'Traceable', label: 'Approvals', detail: 'Workflow history supports audit and compliance.' },
    ],
    framework: ['Process mapping', 'Rule design', 'Workflow build', 'User testing', 'Deployment', 'Optimization'],
    governance: ['Approval logs', 'SLA rules', 'Escalation policy', 'Exception tracking'],
    industries: ['HR operations', 'Finance approvals', 'Procurement', 'Back-office teams'],
    cta: 'Convert manual operations into intelligent workflows.',
  },
  {
    slug: 'ai-business-process-automation',
    title: 'AI & Business Process Automation',
    eyebrow: 'Intelligent Automation',
    subtitle: 'An AI-enabled automation layer for decision logic, process acceleration, and continuous operational learning.',
    description: 'Axinex combines business workflow design with intelligent automation patterns that help teams reduce repetitive decision effort while preserving human oversight.',
    icon: 'psychology',
    visualImage: '/assets/AI_and_business_process_automation.jpeg',
    flowTitle: 'AI Automation Loop',
    flowDescription: 'Business inputs move through intelligence layers, automated actions, human review, and learning cycles.',
    flowNodes: [
      { title: 'Business Inputs', description: 'Requests, documents, data signals, and events feed the automation system.' },
      { title: 'AI Layer', description: 'Classification, recommendations, scoring, and pattern detection support decisions.' },
      { title: 'Decision Logic', description: 'Business rules define when actions should be automated or reviewed.' },
      { title: 'Automated Actions', description: 'Tasks, notifications, updates, and routing happen with reduced manual effort.' },
      { title: 'Continuous Learning', description: 'Performance feedback improves rules, quality, and automation coverage.' },
    ],
    modules: ['AI-Assisted Routing', 'Process Bots', 'Decision Rules', 'Document Workflows', 'Human Review', 'Automation Analytics'],
    impacts: [
      { value: 'Smart', label: 'Routing', detail: 'AI support improves prioritization and assignment.' },
      { value: 'Less', label: 'Repetition', detail: 'Routine process steps become automated.' },
      { value: 'Human', label: 'Control', detail: 'Critical actions remain reviewable and governed.' },
    ],
    framework: ['Use-case selection', 'Data readiness', 'Rule modeling', 'AI workflow setup', 'Pilot automation', 'Scale governance'],
    governance: ['Human-in-loop review', 'Decision audit logs', 'Model usage boundaries', 'Data privacy controls'],
    industries: ['Customer support', 'Document-heavy teams', 'Operations centers', 'Digital service providers'],
    cta: 'Build intelligent automation that stays controlled and business-aligned.',
  },
  {
    slug: 'cybersecurity-management-system',
    title: 'Cybersecurity Management System',
    eyebrow: 'Enterprise Security',
    subtitle: 'A security operations framework for threat visibility, incident response, controls, and recovery readiness.',
    description: 'Axinex cybersecurity management systems help organizations organize protection layers, monitor risks, respond to incidents, and strengthen security governance.',
    icon: 'security',
    visualImage: '/assets/cybersecurity_management_system.jpeg',
    flowTitle: 'Security Operations Flow',
    flowDescription: 'Threat signals move through detection, control, response, recovery, and intelligence improvement.',
    flowNodes: [
      { title: 'Threat Signals', description: 'System events, user activity, alerts, and vulnerabilities feed the security view.' },
      { title: 'Risk Detection', description: 'Potential incidents are classified, prioritized, and assigned for action.' },
      { title: 'Controls', description: 'Access, endpoint, network, application, and data protections reduce exposure.' },
      { title: 'Response', description: 'Incident playbooks guide containment, resolution, communication, and recovery.' },
      { title: 'Security Intelligence', description: 'Reports and lessons learned improve readiness and prevention.' },
    ],
    modules: ['Threat Monitoring', 'Risk Register', 'Incident Response', 'Access Controls', 'Vulnerability Tracking', 'Security Reports'],
    impacts: [
      { value: 'Lower', label: 'Risk', detail: 'Security events become visible and actionable.' },
      { value: 'Faster', label: 'Response', detail: 'Playbooks reduce confusion during incidents.' },
      { value: 'Stronger', label: 'Posture', detail: 'Continuous review improves protection maturity.' },
    ],
    framework: ['Security assessment', 'Control mapping', 'Monitoring setup', 'Incident playbooks', 'Training', 'Ongoing review'],
    governance: ['Access policies', 'Incident records', 'Risk reviews', 'Recovery plans'],
    industries: ['Finance', 'Healthcare', 'SaaS', 'Public sector', 'Enterprise IT'],
    cta: 'Create a controlled security ecosystem for modern operations.',
  },
  {
    slug: 'security-compliance',
    title: 'Security Compliance',
    eyebrow: 'ISO 27001 / SOC2 Ready',
    subtitle: 'A compliance readiness system for policies, controls, evidence, audit trails, and continuous governance.',
    description: 'Axinex helps organizations prepare for compliance programs by structuring security controls, evidence collection, ownership, and audit-ready reporting.',
    icon: 'shield',
    visualImage: '/assets/Security_Compliance.jpeg',
    flowTitle: 'Compliance Readiness Flow',
    flowDescription: 'Policies and controls become measurable evidence, review cycles, and audit-ready documentation.',
    flowNodes: [
      { title: 'Policy Framework', description: 'Security, access, data, operational, and governance policies are structured.' },
      { title: 'Control Mapping', description: 'Requirements are mapped to controls, owners, systems, and evidence needs.' },
      { title: 'Evidence Collection', description: 'Logs, approvals, reviews, screenshots, and records are organized.' },
      { title: 'Audit Readiness', description: 'Gaps, exceptions, and remediation plans are tracked before external review.' },
      { title: 'Continuous Governance', description: 'Recurring reviews keep compliance posture current and accountable.' },
    ],
    modules: ['Policy Library', 'Control Register', 'Evidence Vault', 'Audit Checklist', 'Exception Tracking', 'Compliance Dashboard'],
    impacts: [
      { value: 'Ready', label: 'Audits', detail: 'Evidence and controls are organized before review.' },
      { value: 'Clear', label: 'Ownership', detail: 'Every control has responsible teams and cadence.' },
      { value: 'Continuous', label: 'Governance', detail: 'Compliance becomes an operating rhythm.' },
    ],
    framework: ['Gap assessment', 'Control design', 'Evidence mapping', 'Remediation planning', 'Audit preparation', 'Governance cadence'],
    governance: ['Policy reviews', 'Evidence logs', 'Exception management', 'Control ownership'],
    industries: ['SaaS companies', 'Managed services', 'Finance', 'Healthcare', 'Enterprise vendors'],
    cta: 'Move toward ISO and SOC2 readiness with structured control governance.',
  },
]

const serviceRouteMap: Record<string, string> = {
  'ERP (Enterprise Resource Planning)': 'erp',
  'CRM (Customer Relationship Management)': 'crm',
  'AMS (Annual Maintenance Support)': 'ams',
  'Migration Services': 'migration-services',
  'Cloud Transformation Services': 'cloud-transformation',
  'Cloud Infrastructure Management': 'cloud-infrastructure-management',
  'Identity & Access Management (IAM)': 'identity-access-management',
  'Data Management System': 'data-management-system',
  'Business Intelligence (BI)': 'business-intelligence',
  'Workflow Automation System': 'workflow-automation-system',
  'AI & Business Process Automation': 'ai-business-process-automation',
  'Cybersecurity Management System': 'cybersecurity-management-system',
  'Security Compliance (ISO 27001 / SOC2 Ready)': 'security-compliance',
}

export function getSubsystemHref(service: string) {
  const slug = serviceRouteMap[service]
  return slug ? `/systems/${slug}` : '/contact'
}

export function getSubsystemBySlug(slug: string) {
  return subsystemPages.find((page) => page.slug === slug)
}
